#!/bin/bash

unset TEMPLATECONF
unset OEROOT
if [ -z "$ROOT" ]; then
    ROOT=$(dirname "$THIS_SCRIPT")
    ROOT=$(readlink -f "$ROOT")
fi

echo "---------------------------No platform type provided defailt is imx and careai ---------------------------------"
TEMPLATECONF=${TEMPLATECONF:-$ROOT/meta-agasthya/conf/}

#../poky/oe-init-build-env
if [ -z "$OEROOT" ]; then
    OEROOT=$(dirname sources/poky/oe-init-build-env)
    OEROOT=$(readlink -f "$OEROOT")

fi
echo "conf values"
echo $OEROOT
echo $TEMPLATECONF
POKY="$(pwd)/sources/poky/oe-init-build-env"
source $POKY build
