#!/bin/sh

build="build"
machine="qemux86_64"
if [ "$1" == "" ]; then
	echo " No conf option given"
	exit 1
fi
if [ "$2" == "" ]; then
	echo "Buid dir is "build""
fi
if [ "$3" == "" ]; then
        echo "Machine is "$machine
fi

build=$2
machine=$3

unset TEMPLATECONF
unset OEROOT

if [ -z "$ROOT" ]; then
    ROOT=$(dirname "$THIS_SCRIPT")
    ROOT=$(readlink -f "$ROOT")
fi

TEMPLATECONF=$ROOT/meta-agasthya/conf/${1}

#../poky/oe-init-build-env
if [ -z "$OEROOT" ]; then
    OEROOT=$(dirname ../sources/poky/oe-init-build-env)
    OEROOT=$(readlink -f "$OEROOT")
fi

echo "conf values"
echo "ROOT: "         $ROOT
echo "OEROOT: "       $OEROOT
echo "TEMPLATECONF: " $TEMPLATECONF
echo "MACHINE: "      $machine

POKY="$(pwd)/../sources/poky/oe-init-build-env"
source $POKY $build
MACHINE=$machine bitbake core-image-minimal
