#!/bin/sh

build="build"
boardtype="qemux86_64"
if [ "$1" == "" ]; then
	echo " No conf option given. Default is:"$boardtype
else
	boardtype=$1
fi
if [ "$2" == "" ]; then
	echo "Buid dir is "build""
else
	build=$2
fi

unset TEMPLATECONF
unset OEROOT

if [ -z "$ROOT" ]; then
    ROOT=$(dirname "$THIS_SCRIPT")
    ROOT=$(readlink -f "$ROOT")
fi

TEMPLATECONF=$ROOT/meta-agasthya/conf/${boardtype}

#../poky/oe-init-build-env
if [ -z "$OEROOT" ]; then
    OEROOT=$(dirname ../sources/poky/oe-init-build-env)
    OEROOT=$(readlink -f "$OEROOT")
fi

echo "conf values"
echo "ROOT: "         $ROOT
echo "OEROOT: "       $OEROOT
echo "TEMPLATECONF: " $TEMPLATECONF

POKY="$(pwd)/../sources/poky/oe-init-build-env"
source $POKY $build
